// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: coolScanner.flex



// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int String = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\36\u0200\1\u0300\1\u0400\335\u0200\1\u0500\u1000\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\1\1\1\3\22\0\1\1"+
    "\1\4\1\5\2\0\1\6\1\7\1\0\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\11\21"+
    "\1\0\1\22\1\23\1\24\1\25\2\0\1\26\2\27"+
    "\1\30\1\31\1\27\2\32\1\33\3\32\1\34\1\35"+
    "\1\32\1\36\1\32\1\37\1\40\4\32\1\41\2\32"+
    "\1\42\1\43\1\44\1\45\1\46\1\0\1\47\1\50"+
    "\1\51\1\52\1\53\1\54\1\55\1\56\1\57\1\32"+
    "\1\60\1\61\1\62\1\63\1\64\1\65\1\32\1\66"+
    "\1\67\1\70\1\71\1\72\1\73\1\41\1\74\1\32"+
    "\1\75\1\76\1\77\144\0\1\100\160\0\1\101\u0258\0"+
    "\1\102\165\0\1\103\u01da\0\1\103\2\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1536];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\2\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\2\20\1\21\1\22\1\23\1\24\4\25\1\26\1\27"+
    "\1\30\15\25\1\31\1\1\1\32\1\1\1\33\1\34"+
    "\1\1\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\0\1\44\1\45\1\46\1\0\1\47\1\50\1\51"+
    "\11\25\1\52\1\25\1\53\14\25\1\54\1\0\1\33"+
    "\3\0\2\44\1\55\11\25\1\56\1\25\1\57\1\60"+
    "\1\61\1\25\1\62\4\25\1\63\5\25\1\64\2\0"+
    "\1\44\4\25\1\65\3\25\1\66\2\25\1\67\1\70"+
    "\1\25\1\71\3\25\1\72\1\73\2\25\1\74\2\25"+
    "\1\75\1\76\3\25\1\77\3\25\1\100\4\25\1\101"+
    "\1\25\1\102\1\103\1\104\10\25\1\105\4\25\1\106"+
    "\56\25\1\107\3\25\1\107\3\25\1\107\3\25\1\107"+
    "\2\25\1\107\1\25\1\107\1\25\1\107\1\25\1\107"+
    "\1\25\1\107\1\25\1\107\1\25\1\107\1\25\1\107";

  private static int [] zzUnpackAction() {
    int [] result = new int[263];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\104\0\210\0\210\0\210\0\314\0\u0110\0\210"+
    "\0\210\0\u0154\0\210\0\210\0\u0198\0\u01dc\0\210\0\u0220"+
    "\0\210\0\u0264\0\u02a8\0\u02ec\0\210\0\u0330\0\u0374\0\u03b8"+
    "\0\u03fc\0\u0440\0\u0484\0\u04c8\0\210\0\210\0\210\0\u050c"+
    "\0\u0550\0\u0594\0\u05d8\0\u061c\0\u0660\0\u06a4\0\u06e8\0\u072c"+
    "\0\u0770\0\u07b4\0\u07f8\0\u083c\0\210\0\u0880\0\210\0\u08c4"+
    "\0\u0908\0\210\0\u094c\0\210\0\210\0\210\0\210\0\210"+
    "\0\210\0\210\0\u0990\0\u09d4\0\210\0\u0a18\0\u0a5c\0\210"+
    "\0\210\0\210\0\u0aa0\0\u0ae4\0\u0b28\0\u0b6c\0\u0bb0\0\u0bf4"+
    "\0\u0c38\0\u0c7c\0\u0cc0\0\u0aa0\0\u0d04\0\u0aa0\0\u0d48\0\u0d8c"+
    "\0\u0dd0\0\u0e14\0\u0e58\0\u0e9c\0\u0ee0\0\u0f24\0\u0f68\0\u0fac"+
    "\0\u0ff0\0\u1034\0\210\0\u1078\0\210\0\u10bc\0\u1100\0\u1144"+
    "\0\210\0\u1188\0\u0a5c\0\u11cc\0\u1210\0\u1254\0\u1298\0\u12dc"+
    "\0\u1320\0\u1364\0\u13a8\0\u13ec\0\u11cc\0\u1430\0\u11cc\0\u11cc"+
    "\0\u11cc\0\u1474\0\u11cc\0\u14b8\0\u14fc\0\u1540\0\u1584\0\u11cc"+
    "\0\u15c8\0\u160c\0\u1650\0\u1694\0\u16d8\0\210\0\u171c\0\u1760"+
    "\0\u1100\0\u17a4\0\u17e8\0\u182c\0\u1870\0\u17a4\0\u18b4\0\u18f8"+
    "\0\u193c\0\u17a4\0\u1980\0\u19c4\0\u17a4\0\u17a4\0\u1a08\0\u17a4"+
    "\0\u1a4c\0\u1a90\0\u1ad4\0\u17a4\0\u17a4\0\u1b18\0\u1b5c\0\u1b5c"+
    "\0\u1ba0\0\u1be4\0\u1b5c\0\u1b5c\0\u1c28\0\u1c6c\0\u1cb0\0\u1b5c"+
    "\0\u1cf4\0\u1d38\0\u1d7c\0\u1b5c\0\u1dc0\0\u1e04\0\u1e48\0\u1e8c"+
    "\0\u1dc0\0\u1ed0\0\u1dc0\0\u1dc0\0\u1dc0\0\u1f14\0\u1f58\0\u1f9c"+
    "\0\u1fe0\0\u2024\0\u2068\0\u20ac\0\u20f0\0\u2068\0\u2134\0\u2178"+
    "\0\u21bc\0\u2200\0\u2178\0\u2244\0\u2288\0\u22cc\0\u2310\0\u2354"+
    "\0\u2398\0\u23dc\0\u2420\0\u2464\0\u24a8\0\u24ec\0\u2530\0\u2574"+
    "\0\u25b8\0\u25fc\0\u2640\0\u2684\0\u26c8\0\u270c\0\u2750\0\u2794"+
    "\0\u27d8\0\u281c\0\u2860\0\u28a4\0\u28e8\0\u292c\0\u2970\0\u29b4"+
    "\0\u29f8\0\u2a3c\0\u2a80\0\u2ac4\0\u2b08\0\u2b4c\0\u2b90\0\u2bd4"+
    "\0\u2c18\0\u2c5c\0\u2ca0\0\u2ce4\0\u2d28\0\u2d6c\0\u2db0\0\u2df4"+
    "\0\u2e38\0\u2e38\0\u2e7c\0\u2ec0\0\u2f04\0\u2f48\0\u2f8c\0\u2fd0"+
    "\0\u3014\0\u3058\0\u309c\0\u30e0\0\u3124\0\u3124\0\u3168\0\u31ac"+
    "\0\u31ac\0\u31f0\0\u3234\0\u3278\0\u32bc\0\u3300\0\u3344\0\u3388"+
    "\0\u33cc\0\u3410\0\u3454\0\u3498\0\u34dc\0\210\0\u3520";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[263];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\6\32\1\34\2\32\1\35\1\3\1\36\1\37"+
    "\1\3\1\32\1\40\1\41\1\32\1\42\1\43\2\32"+
    "\1\44\1\32\1\45\1\32\1\46\1\32\1\47\1\50"+
    "\1\51\1\52\1\32\1\53\1\54\1\32\1\55\1\56"+
    "\1\57\1\60\3\3\2\61\2\3\1\61\1\62\35\61"+
    "\1\63\40\61\106\0\1\5\125\0\1\64\66\0\1\65"+
    "\120\0\1\66\72\0\1\67\10\0\1\70\74\0\1\71"+
    "\6\0\1\72\71\0\1\73\4\0\1\74\4\0\1\75"+
    "\75\0\1\76\1\0\2\24\17\0\1\77\60\0\1\76"+
    "\1\0\2\24\106\0\1\100\103\0\1\101\103\0\1\102"+
    "\77\0\2\103\4\0\14\103\4\0\20\103\1\104\6\103"+
    "\27\0\2\103\4\0\14\103\4\0\27\103\27\0\2\103"+
    "\4\0\14\103\4\0\5\103\1\105\21\103\27\0\2\103"+
    "\4\0\14\103\4\0\5\103\1\106\21\103\27\0\2\103"+
    "\4\0\14\103\4\0\16\103\1\107\1\103\1\110\6\103"+
    "\27\0\2\103\4\0\14\103\4\0\13\103\1\111\2\103"+
    "\1\112\10\103\27\0\2\103\4\0\14\103\4\0\13\103"+
    "\1\113\13\103\27\0\2\103\4\0\14\103\4\0\11\103"+
    "\1\114\4\103\1\115\10\103\27\0\2\103\4\0\14\103"+
    "\4\0\6\103\1\116\6\103\1\117\11\103\27\0\2\103"+
    "\4\0\14\103\4\0\5\103\1\120\10\103\1\121\10\103"+
    "\27\0\2\103\4\0\14\103\4\0\5\103\1\122\21\103"+
    "\27\0\2\103\4\0\14\103\4\0\16\103\1\123\1\103"+
    "\1\124\6\103\27\0\2\103\4\0\14\103\4\0\5\103"+
    "\1\125\10\103\1\126\10\103\27\0\2\103\4\0\14\103"+
    "\4\0\22\103\1\127\4\103\27\0\2\103\4\0\14\103"+
    "\4\0\10\103\1\130\16\103\27\0\2\103\4\0\14\103"+
    "\4\0\16\103\1\131\10\103\27\0\2\103\4\0\14\103"+
    "\4\0\10\103\1\132\16\103\105\0\1\133\107\0\1\134"+
    "\1\0\2\61\2\0\1\61\1\0\35\61\1\0\40\61"+
    "\43\0\1\135\17\0\1\135\2\0\1\135\1\0\1\135"+
    "\7\0\1\136\3\0\12\137\1\140\71\137\2\74\1\141"+
    "\1\142\1\74\1\0\35\74\1\0\40\74\20\0\2\76"+
    "\102\0\2\143\4\0\4\143\15\0\6\143\47\0\2\144"+
    "\4\0\14\144\4\0\27\144\27\0\2\144\4\0\14\144"+
    "\4\0\20\144\1\145\6\144\27\0\2\144\4\0\14\144"+
    "\4\0\3\144\1\146\23\144\27\0\2\144\4\0\14\144"+
    "\4\0\1\144\1\147\25\144\27\0\2\144\4\0\14\144"+
    "\4\0\16\144\1\150\10\144\27\0\2\144\4\0\14\144"+
    "\4\0\5\144\1\151\21\144\27\0\2\144\4\0\14\144"+
    "\4\0\1\144\1\152\25\144\27\0\2\144\4\0\14\144"+
    "\4\0\15\144\1\153\11\144\27\0\2\144\4\0\14\144"+
    "\4\0\21\144\1\154\5\144\27\0\2\144\4\0\14\144"+
    "\4\0\20\144\1\155\6\144\27\0\2\144\4\0\14\144"+
    "\4\0\1\156\21\144\1\157\4\144\27\0\2\144\4\0"+
    "\14\144\4\0\15\144\1\160\4\144\1\161\4\144\27\0"+
    "\2\144\4\0\14\144\4\0\16\144\1\162\10\144\27\0"+
    "\2\144\4\0\14\144\4\0\25\144\1\163\1\144\27\0"+
    "\2\144\4\0\14\144\4\0\16\144\1\164\10\144\27\0"+
    "\2\144\4\0\14\144\4\0\11\144\1\165\15\144\27\0"+
    "\2\144\4\0\14\144\4\0\1\144\1\166\20\144\1\167"+
    "\4\144\27\0\2\144\4\0\14\144\4\0\6\144\1\170"+
    "\20\144\27\0\2\144\4\0\14\144\4\0\1\144\1\171"+
    "\16\144\1\172\6\144\27\0\2\144\4\0\14\144\4\0"+
    "\5\144\1\173\21\144\27\0\2\144\4\0\14\144\4\0"+
    "\11\144\1\174\15\144\27\0\2\144\4\0\14\144\4\0"+
    "\11\144\1\175\15\144\110\0\1\176\104\0\1\177\1\0"+
    "\12\137\1\200\103\137\1\200\4\137\1\201\64\137\2\0"+
    "\1\141\121\0\2\202\4\0\14\202\4\0\27\202\27\0"+
    "\2\202\4\0\14\202\4\0\1\202\1\203\25\202\27\0"+
    "\2\202\4\0\14\202\4\0\11\202\1\204\15\202\27\0"+
    "\2\202\4\0\14\202\4\0\13\202\1\205\13\202\27\0"+
    "\2\202\4\0\14\202\4\0\13\202\1\206\13\202\27\0"+
    "\2\202\4\0\14\202\4\0\1\202\1\207\25\202\27\0"+
    "\2\202\4\0\14\202\4\0\21\202\1\210\5\202\27\0"+
    "\2\202\4\0\14\202\4\0\22\202\1\211\4\202\27\0"+
    "\2\202\4\0\14\202\4\0\5\202\1\212\21\202\27\0"+
    "\2\202\4\0\14\202\4\0\11\202\1\213\7\202\1\214"+
    "\5\202\27\0\2\202\4\0\14\202\4\0\17\202\1\215"+
    "\7\202\27\0\2\202\4\0\14\202\4\0\13\202\1\216"+
    "\13\202\27\0\2\202\4\0\14\202\4\0\15\202\1\217"+
    "\11\202\27\0\2\202\4\0\14\202\4\0\13\202\1\220"+
    "\13\202\27\0\2\202\4\0\14\202\4\0\23\202\1\221"+
    "\3\202\27\0\2\202\4\0\14\202\4\0\22\202\1\222"+
    "\4\202\27\0\2\202\4\0\14\202\4\0\11\202\1\223"+
    "\15\202\27\0\2\202\4\0\14\202\4\0\15\202\1\224"+
    "\11\202\27\0\2\202\4\0\14\202\4\0\4\202\1\225"+
    "\22\202\27\0\2\202\4\0\14\202\4\0\13\202\1\226"+
    "\13\202\112\0\1\135\12\137\1\200\4\137\1\141\64\137"+
    "\20\0\2\227\4\0\14\227\4\0\27\227\27\0\2\227"+
    "\4\0\14\227\4\0\26\227\1\230\27\0\2\227\4\0"+
    "\14\227\4\0\14\227\1\231\12\227\27\0\2\227\4\0"+
    "\7\227\1\232\4\227\4\0\27\227\27\0\2\227\4\0"+
    "\14\227\4\0\12\227\1\233\14\227\27\0\2\227\4\0"+
    "\14\227\4\0\21\227\1\234\5\227\27\0\2\227\4\0"+
    "\14\227\4\0\11\227\1\235\15\227\27\0\2\227\4\0"+
    "\14\227\4\0\15\227\1\236\11\227\27\0\2\227\4\0"+
    "\14\227\4\0\22\227\1\237\4\227\27\0\2\227\4\0"+
    "\14\227\4\0\22\227\1\240\4\227\27\0\2\227\4\0"+
    "\14\227\4\0\20\227\1\241\6\227\27\0\2\227\4\0"+
    "\14\227\4\0\11\227\1\242\15\227\27\0\2\227\4\0"+
    "\14\227\4\0\15\227\1\243\11\227\27\0\2\227\4\0"+
    "\14\227\4\0\5\227\1\244\21\227\27\0\2\245\4\0"+
    "\14\245\4\0\27\245\27\0\2\245\4\0\14\245\4\0"+
    "\1\245\1\246\25\245\27\0\2\245\4\0\14\245\4\0"+
    "\23\245\1\247\3\245\27\0\2\245\4\0\14\245\4\0"+
    "\15\245\1\250\11\245\27\0\2\245\4\0\14\245\4\0"+
    "\22\245\1\251\4\245\27\0\2\245\4\0\14\245\4\0"+
    "\20\245\1\252\6\245\27\0\2\245\4\0\14\245\4\0"+
    "\15\245\1\253\11\245\27\0\2\245\4\0\14\245\4\0"+
    "\3\245\1\254\23\245\27\0\2\245\4\0\14\245\4\0"+
    "\7\245\1\255\17\245\27\0\2\256\4\0\14\256\4\0"+
    "\27\256\27\0\2\256\4\0\14\256\4\0\13\256\1\257"+
    "\13\256\27\0\2\256\4\0\14\256\4\0\14\256\1\260"+
    "\12\256\27\0\2\256\4\0\14\256\4\0\23\256\1\261"+
    "\3\256\27\0\2\256\4\0\14\256\4\0\11\256\1\262"+
    "\15\256\27\0\2\263\4\0\14\263\4\0\27\263\27\0"+
    "\2\263\4\0\5\263\1\264\6\263\4\0\27\263\27\0"+
    "\2\263\4\0\14\263\4\0\2\263\1\265\24\263\27\0"+
    "\2\263\4\0\14\263\4\0\5\263\1\266\21\263\27\0"+
    "\2\263\4\0\14\263\4\0\15\263\1\267\11\263\27\0"+
    "\2\270\4\0\14\270\4\0\27\270\27\0\2\270\4\0"+
    "\14\270\4\0\15\270\1\271\11\270\27\0\2\270\4\0"+
    "\14\270\4\0\5\270\1\272\21\270\27\0\2\270\4\0"+
    "\14\270\4\0\7\270\1\273\17\270\27\0\2\274\4\0"+
    "\14\274\4\0\27\274\27\0\2\274\4\0\14\274\4\0"+
    "\22\274\1\275\4\274\27\0\2\274\4\0\14\274\4\0"+
    "\20\274\1\276\6\274\27\0\2\277\4\0\14\277\4\0"+
    "\27\277\27\0\2\277\4\0\14\277\4\0\5\277\1\300"+
    "\21\277\27\0\2\277\4\0\3\277\1\301\10\277\4\0"+
    "\5\277\1\301\21\277\27\0\2\302\4\0\14\302\4\0"+
    "\27\302\27\0\2\302\4\0\14\302\4\0\7\302\1\303"+
    "\17\302\27\0\2\302\4\0\6\302\1\304\1\302\1\305"+
    "\3\302\4\0\27\302\27\0\2\306\4\0\14\306\4\0"+
    "\27\306\27\0\2\306\4\0\14\306\4\0\5\306\1\307"+
    "\21\306\27\0\2\306\4\0\14\306\4\0\11\306\1\310"+
    "\15\306\27\0\2\306\4\0\14\306\4\0\13\306\1\311"+
    "\13\306\27\0\2\312\4\0\14\312\4\0\27\312\27\0"+
    "\2\312\4\0\14\312\4\0\20\312\1\313\6\312\27\0"+
    "\2\312\4\0\14\312\4\0\15\312\1\314\11\312\27\0"+
    "\2\312\4\0\14\312\4\0\23\312\1\315\3\312\27\0"+
    "\2\316\4\0\14\316\4\0\27\316\27\0\2\316\4\0"+
    "\3\316\1\317\10\316\4\0\5\316\1\317\21\316\27\0"+
    "\2\316\4\0\14\316\4\0\23\316\1\320\3\316\27\0"+
    "\2\316\4\0\14\316\4\0\21\316\1\321\5\316\27\0"+
    "\2\322\4\0\14\322\4\0\27\322\27\0\2\322\4\0"+
    "\6\322\1\323\1\322\1\324\3\322\4\0\27\322\27\0"+
    "\2\322\4\0\14\322\4\0\21\322\1\325\5\322\27\0"+
    "\2\322\4\0\12\322\1\326\1\322\4\0\27\322\27\0"+
    "\2\327\4\0\14\327\4\0\27\327\27\0\2\327\4\0"+
    "\14\327\4\0\11\327\1\330\15\327\27\0\2\327\4\0"+
    "\14\327\4\0\13\327\1\331\13\327\27\0\2\327\4\0"+
    "\12\327\1\332\1\327\4\0\27\327\27\0\2\327\4\0"+
    "\14\327\4\0\11\327\1\333\15\327\27\0\2\334\4\0"+
    "\14\334\4\0\27\334\27\0\2\334\4\0\14\334\4\0"+
    "\15\334\1\335\11\334\27\0\2\334\4\0\14\334\4\0"+
    "\23\334\1\336\3\334\27\0\2\334\4\0\14\334\4\0"+
    "\11\334\1\337\15\334\27\0\2\334\4\0\14\334\4\0"+
    "\7\334\1\340\17\334\27\0\2\341\4\0\14\341\4\0"+
    "\27\341\27\0\2\341\4\0\14\341\4\0\23\341\1\342"+
    "\3\341\27\0\2\341\4\0\14\341\4\0\21\341\1\343"+
    "\5\341\27\0\2\341\4\0\14\341\4\0\7\341\1\344"+
    "\17\341\27\0\2\341\4\0\14\341\4\0\15\341\1\345"+
    "\11\341\27\0\2\346\4\0\14\346\4\0\27\346\27\0"+
    "\2\346\4\0\14\346\4\0\21\346\1\347\5\346\27\0"+
    "\2\346\4\0\12\346\1\350\1\346\4\0\27\346\27\0"+
    "\2\346\4\0\14\346\4\0\15\346\1\351\11\346\27\0"+
    "\2\352\4\0\14\346\4\0\27\346\27\0\2\353\4\0"+
    "\14\353\4\0\27\353\27\0\2\353\4\0\12\353\1\354"+
    "\1\353\4\0\27\353\27\0\2\353\4\0\14\353\4\0"+
    "\11\353\1\355\15\353\27\0\2\356\4\0\14\353\4\0"+
    "\27\353\27\0\2\357\4\0\14\357\4\0\27\357\27\0"+
    "\2\357\4\0\14\357\4\0\11\357\1\360\15\357\27\0"+
    "\2\357\4\0\14\357\4\0\7\357\1\361\17\357\27\0"+
    "\2\362\4\0\14\357\4\0\27\357\27\0\2\363\4\0"+
    "\14\363\4\0\27\363\27\0\2\363\4\0\14\363\4\0"+
    "\7\363\1\364\17\363\27\0\2\363\4\0\14\363\4\0"+
    "\15\363\1\365\11\363\27\0\2\366\4\0\14\363\4\0"+
    "\27\363\27\0\2\367\4\0\14\367\4\0\27\367\27\0"+
    "\2\367\4\0\14\367\4\0\15\367\1\370\11\367\27\0"+
    "\2\371\4\0\14\367\4\0\27\367\27\0\2\372\4\0"+
    "\14\372\4\0\27\372\27\0\2\373\4\0\14\372\4\0"+
    "\27\372\27\0\2\374\4\0\14\374\4\0\27\374\27\0"+
    "\2\375\4\0\14\374\4\0\27\374\27\0\2\376\4\0"+
    "\14\376\4\0\27\376\27\0\2\377\4\0\14\376\4\0"+
    "\27\376\27\0\2\u0100\4\0\14\u0100\4\0\27\u0100\27\0"+
    "\2\u0101\4\0\14\u0100\4\0\27\u0100\27\0\2\u0102\4\0"+
    "\14\u0102\4\0\27\u0102\27\0\2\u0103\4\0\14\u0102\4\0"+
    "\27\u0102\27\0\2\u0104\4\0\14\u0104\4\0\27\u0104\27\0"+
    "\2\u0105\4\0\14\u0104\4\0\27\u0104\27\0\2\u0106\4\0"+
    "\14\u0106\4\0\27\u0106\27\0\2\u0107\4\0\14\u0106\4\0"+
    "\27\u0106\27\0\2\u0107\62\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[13668];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\3\11\2\1\2\11\1\1\2\11\2\1\1\11"+
    "\1\1\1\11\3\1\1\11\7\1\3\11\15\1\1\11"+
    "\1\1\1\11\2\1\1\11\1\1\7\11\1\0\1\1"+
    "\1\11\1\1\1\0\3\11\30\1\1\11\1\0\1\11"+
    "\3\0\1\11\34\1\1\11\2\0\205\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[263];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    public int ICV = 0;
    public boolean BOOL = false;
    public double REAL = 0;
    public StringBuilder string = new StringBuilder();

    private double getValueOfScientificNumber(String scientific) {
        int index = 0;
        if (scientific.contains("e"))
            index = scientific.indexOf("e");
        else if (scientific.contains("E"))
            index = scientific.indexOf("E");
        double value = 0;
        if (index > 0) {
            int base = Integer.parseInt(scientific.substring(0, index));
            int exp = Integer.parseInt(scientific.substring(index + 1));
            value = base * Math.pow(10, exp);
        } else if (index < 0)
            value = Double.parseDouble(scientific);
        else
            throw new NumberFormatException();
        return value;
    }

    private int getValueOfHexadecimalNumber(String hex) {
        String pureHex = hex.charAt(0) == '-' ? "-" + hex.substring(3) : hex.substring(2);
        return Integer.parseInt(pureHex, 16);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Scanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Symbol nextToken() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new RuntimeException("Illegal character \"" + yytext() + "\" at line "+yyline+", column " + yycolumn);
            }
            // fall through
          case 72: break;
          case 2:
            { /* ignore */
            }
            // fall through
          case 73: break;
          case 3:
            { return new Symbol("lineTerminate");
            }
            // fall through
          case 74: break;
          case 4:
            { return (new Symbol("!"));
            }
            // fall through
          case 75: break;
          case 5:
            { yybegin(String);
        string.setLength(0);
        string.append("\"");
            }
            // fall through
          case 76: break;
          case 6:
            { return (new Symbol("%"));
            }
            // fall through
          case 77: break;
          case 7:
            { return (new Symbol("&"));
            }
            // fall through
          case 78: break;
          case 8:
            { return (new Symbol("("));
            }
            // fall through
          case 79: break;
          case 9:
            { return (new Symbol(")"));
            }
            // fall through
          case 80: break;
          case 10:
            { return (new Symbol("*"));
            }
            // fall through
          case 81: break;
          case 11:
            { return (new Symbol("+"));
            }
            // fall through
          case 82: break;
          case 12:
            { return (new Symbol(","));
            }
            // fall through
          case 83: break;
          case 13:
            { return (new Symbol("-"));
            }
            // fall through
          case 84: break;
          case 14:
            { return (new Symbol("."));
            }
            // fall through
          case 85: break;
          case 15:
            { return (new Symbol("/"));
            }
            // fall through
          case 86: break;
          case 16:
            { ICV = Integer.parseInt(yytext());
        return new Symbol("decimal", ICV);
            }
            // fall through
          case 87: break;
          case 17:
            { return (new Symbol(";"));
            }
            // fall through
          case 88: break;
          case 18:
            { return (new Symbol("<"));
            }
            // fall through
          case 89: break;
          case 19:
            { return (new Symbol("="));
            }
            // fall through
          case 90: break;
          case 20:
            { return (new Symbol(">"));
            }
            // fall through
          case 91: break;
          case 21:
            { return new Symbol("identifier", yytext());
            }
            // fall through
          case 92: break;
          case 22:
            { return (new Symbol("["));
            }
            // fall through
          case 93: break;
          case 23:
            { return (new Symbol("]"));
            }
            // fall through
          case 94: break;
          case 24:
            { return (new Symbol("^"));
            }
            // fall through
          case 95: break;
          case 25:
            { return (new Symbol("{"));
            }
            // fall through
          case 96: break;
          case 26:
            { return (new Symbol("}"));
            }
            // fall through
          case 97: break;
          case 27:
            { string.append(yytext());
            }
            // fall through
          case 98: break;
          case 28:
            { yybegin(YYINITIAL);
        string.append("\"");
        StringBuilder temp = string;
        string = new StringBuilder();
        return new Symbol("stringLiteral", temp.toString());
            }
            // fall through
          case 99: break;
          case 29:
            { return (new Symbol("!="));
            }
            // fall through
          case 100: break;
          case 30:
            { return (new Symbol("&&"));
            }
            // fall through
          case 101: break;
          case 31:
            { return (new Symbol("*="));
            }
            // fall through
          case 102: break;
          case 32:
            { return (new Symbol("++"));
            }
            // fall through
          case 103: break;
          case 33:
            { return (new Symbol("+="));
            }
            // fall through
          case 104: break;
          case 34:
            { return (new Symbol("--"));
            }
            // fall through
          case 105: break;
          case 35:
            { return (new Symbol("-="));
            }
            // fall through
          case 106: break;
          case 36:
            { return new Symbol("comment", yytext());
            }
            // fall through
          case 107: break;
          case 37:
            { return (new Symbol("/="));
            }
            // fall through
          case 108: break;
          case 38:
            { REAL = Double.valueOf(yytext());
        return new Symbol("realNumber", REAL);
            }
            // fall through
          case 109: break;
          case 39:
            { return (new Symbol("<="));
            }
            // fall through
          case 110: break;
          case 40:
            { return (new Symbol("=="));
            }
            // fall through
          case 111: break;
          case 41:
            { return (new Symbol(">="));
            }
            // fall through
          case 112: break;
          case 42:
            { return (new Symbol("fi"));
            }
            // fall through
          case 113: break;
          case 43:
            { return (new Symbol("if"));
            }
            // fall through
          case 114: break;
          case 44:
            { return (new Symbol("|"));
            }
            // fall through
          case 115: break;
          case 45:
            { ICV = getValueOfHexadecimalNumber(yytext());
        return new Symbol("hexadecimal", ICV);
            }
            // fall through
          case 116: break;
          case 46:
            { return (new Symbol("for"));
            }
            // fall through
          case 117: break;
          case 47:
            { return (new Symbol("int", yytext()));
            }
            // fall through
          case 118: break;
          case 48:
            { return (new Symbol("len"));
            }
            // fall through
          case 119: break;
          case 49:
            { return (new Symbol("let"));
            }
            // fall through
          case 120: break;
          case 50:
            { return (new Symbol("new"));
            }
            // fall through
          case 121: break;
          case 51:
            { return (new Symbol("rof"));
            }
            // fall through
          case 122: break;
          case 52:
            { return (new Symbol("“"));
            }
            // fall through
          case 123: break;
          case 53:
            { return (new Symbol("bool", yytext()));
            }
            // fall through
          case 124: break;
          case 54:
            { return (new Symbol("else"));
            }
            // fall through
          case 125: break;
          case 55:
            { return (new Symbol("loop"));
            }
            // fall through
          case 126: break;
          case 56:
            { return (new Symbol("pool"));
            }
            // fall through
          case 127: break;
          case 57:
            { return (new Symbol("real"));
            }
            // fall through
          case 128: break;
          case 58:
            { return (new Symbol("then"));
            }
            // fall through
          case 129: break;
          case 59:
            { return (new Symbol("void"));
            }
            // fall through
          case 130: break;
          case 60:
            { return (new Symbol("Array"));
            }
            // fall through
          case 131: break;
          case 61:
            { return (new Symbol("break"));
            }
            // fall through
          case 132: break;
          case 62:
            { return (new Symbol("class"));
            }
            // fall through
          case 133: break;
          case 63:
            { return (new Symbol("print"));
            }
            // fall through
          case 134: break;
          case 64:
            { return (new Symbol("while"));
            }
            // fall through
          case 135: break;
          case 65:
            { return (new Symbol("in_int"));
            }
            // fall through
          case 136: break;
          case 66:
            { return (new Symbol("return"));
            }
            // fall through
          case 137: break;
          case 67:
            { return (new Symbol("static"));
            }
            // fall through
          case 138: break;
          case 68:
            { return (new Symbol("string", yytext()));
            }
            // fall through
          case 139: break;
          case 69:
            { return (new Symbol("continue"));
            }
            // fall through
          case 140: break;
          case 70:
            { return (new Symbol("in_string"));
            }
            // fall through
          case 141: break;
          case 71:
            { REAL = getValueOfScientificNumber(yytext());
        return new Symbol("scientificNotation", REAL);
            }
            // fall through
          case 142: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
